In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [4]:
import numpy as np #あ import numpy and assign an alias named np

In [5]:
np.__version__ #checking the version by using the alias since we assigned it already

'2.0.2'

In [6]:
print(dir(np)) #checking the content of numpy module

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

### Part A: Creating an `ndarray`

In [7]:
#values I used 1 - 9
python_list_A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

A = np.array(python_list_A)

print("Our NumPy array A:")
print(A)

Our NumPy array A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 1. Using a property of the `ndarray` object (`A.shape`)

In [8]:
# The 'shape' property returns a tuple indicating the size of each dimension of the array.
# For a 3x3 array, it will return (3, 3).
print("Shape of array A:", A.shape)

Shape of array A: (3, 3)


#### 2. Using a method of the `ndarray` object (`A.max()`)

In [9]:
# The 'max()' method returns the maximum value present in the array inside of it.
print("Maximum value in array A :", A.max())

Maximum value in array A : 9


#### 3. Using a NumPy function and passing an `ndarray` (`np.max(A)`)

In [10]:
print("Maximum value in array A (using NumPy function):", np.max(A))

Maximum value in array A (using NumPy function): 9


### Part B: Create a 5x5 integer-array filled with ones and check its properties

In [11]:
#valus will increment

B_array = np.ones((5, 5), dtype=int)
print("The 5x5 integer array filled with ones:")
print(B_array)

# This will return a tuple indicating the dimensions (rows, columns).

print("\nShape of B_array:", B_array.shape)

# This will return the total number of elements in the array (rows * columns).

print("Size of B_array:", B_array.size)

# This will return an integer representing the number of dimensions.

print("Number of dimensions of B_array:", B_array.ndim)

The 5x5 integer array filled with ones:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Shape of B_array: (5, 5)
Size of B_array: 25
Number of dimensions of B_array: 2


### Part C: Create an array from -5 to +5, multiply by 2, and print

In [12]:
# Create an array of values from -5 to 5 using np.arange()
# np.arange(-5, 6) generates numbers from -5 up to (but not including) 6, which covers -5 to 5.

C_array = np.arange(-5, 6)

print("Original array (C_array):")
print(C_array)

# Multiply each value in the array by 2
# NumPy arrays support element-wise operations, so C_array * 2 multiplies each element by 2.

C_array_multiplied = C_array * 2

print("\nArray after multiplying each value by 2:")
print(C_array_multiplied)


Original array (C_array):
[-5 -4 -3 -2 -1  0  1  2  3  4  5]

Array after multiplying each value by 2:
[-10  -8  -6  -4  -2   0   2   4   6   8  10]
